### ISSUE TITLE
Pricing missing when search from url

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-airbnb-scraper#22]
https://my.apify.com/view/runs/vhQK9JyweSmeHPpJm

**Comment by dtrungtin** [comment]
I would say it's improvement as the current airbnb v2 API doesn't return pricing.

**Comment by zpelechova** [comment]
Well it is very confusing for the user why when search New York, I get the prices, and when I search https://cs.airbnb.com/s/New-York--NY--United-States/homes I get different results :)

**Comment by dtrungtin** [comment]
Fixed. https://github.com/dtrungtin/actor-airbnb-scraper/commit/c33286c6f4621e61a49946b2321f3b54c04440a9
Must provide valid checkIn & checkOut.

**Comment by zpelechova** [comment]
Sorry, just to be clear - if I provide place, I dont have to provide check in checkout and when I provide URL I have to? How does it work?

**Comment by dtrungtin** [comment]
Yes, if provide URL must provide checkIn & checkOut.

**Comment by zpelechova** [comment]
I still dont get the price for example here: https://my.apify.com/view/runs/hw6EC9GBRFl5NTzEJ

**Comment by zpelechova** [comment]
Also it would make sence to have the check-in/out dates also in output.

**Comment by zpelechova** [comment]
Tried again, tried with diff proxies (shader, automatic, residentials), still nothing: https://my.apify.com/view/runs/xCeEjpfku0yeYpDRm

**Comment by dtrungtin** [comment]
) Cannot fetch input from the key-value store: i: Authentication token is not valid
Please share with permission to read the input.

**Comment by dtrungtin** [comment]
"https://www.airbnb.com/rooms/16677866?check_in=2021-10-01&check_out=2021-10-08&federated_search_id=afec8ea5-15cd-47d5-bc81-99ca0fdd925d&source_impression_id=p3_1621933188_ceKT5dcBQ9bdcgRI&guests=1&adults=1"
Please try with valid check-in & check-out. The room is not available at check_in=2021-10-01 & check_out=2021-10-08.
Note that the checkin & checkout gotten from the url. If not, it will get from the actor input.

https://my.apify.com/tasks/bqwJe7wcuwVwedRLQ#/runs/L5lbetpAY04Qs6Ab3

**Comment by zpelechova** [comment]
Fixed 07/21.
